version: "3.8"
volumes:
  psql:
services:
  test-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - psql:/var/lib/postgres/data
      - ./psql_init:/docker-entrypoint-initdb.d
    ports:
      - 5555:5432
